### ISSUE TITLE
MaskRCNN training failure issue

### ISSUE THREAD

**Issue by Riyank7** [olgaliak/segmentation-unet-maskrcnn#4]
(tensorflow) C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN>python main_train.py --train C:\Users\Lenovo\segmentation-unet-maskrcnn\data\maskRCNN --valid C:\Users\Lenovo\segmentation-unet-maskrcnn\data\maskRCNN --hill True --epoch 3 --output C:\Users\Lenovo\segmentation-unet-maskrcnn\data\maskRCNN
Using TensorFlow backend.
read training data for maskRCNN ...
image_dir is C:\Users\Lenovo\segmentation-unet-maskrcnn\data\maskRCNN\jpg4
read validating data for maskRCNN ...
image_dir is C:\Users\Lenovo\segmentation-unet-maskrcnn\data\maskRCNN\jpg4
2019-05-07 19:09:43.434199: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
In model:  rpn_model
WARNING:tensorflow:From C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py:2045: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
ERROR:root:Error processing image {'id': 3, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\fieldborders_19_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_19_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_19_4109150_merged_waterways.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_19_4109150_merged_terraces.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_19_4109150_merged_wsb.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders' is not in list
ERROR:root:Error processing image {'id': 37, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\wsb_753_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\wsb_753_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\wsb_753_4109150_merged_waterways.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\wsb_753_4109150_merged_fieldborders.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\wsb_753_4109150_merged_terraces.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\wsb' is not in list
ERROR:root:Error processing image {'id': 23, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\waterways_1304_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_1304_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_1304_4109150_merged_fieldborders.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_1304_4109150_merged_terraces.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_1304_4109150_merged_wsb.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways' is not in list
ERROR:root:Error processing image {'id': 29, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\waterways_938_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_938_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_938_4109150_merged_fieldborders.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_938_4109150_merged_terraces.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways_938_4109150_merged_wsb.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\waterways' is not in list
ERROR:root:Error processing image {'id': 18, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\terraces_587_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\terraces_587_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\terraces_587_4109150_merged_waterways.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\terraces_587_4109150_merged_fieldborders.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\terraces_587_4109150_merged_wsb.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\terraces' is not in list
ERROR:root:Error processing image {'id': 4, 'source': 'shapes', 'path': 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\jpg4\\fieldborders_24_4109150_merged.jpg', 'mask_path': ['C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_24_4109150_merged.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_24_4109150_merged_waterways.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_24_4109150_merged_terraces.jpg', 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders_24_4109150_merged_wsb.jpg'], 'width': 224, 'height': 224}
Traceback (most recent call last):
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders' is not in list
Traceback (most recent call last):
  File "main_train.py", line 106, in <module>
    layers='all')
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 2198, in train
    validation_data=next(val_generator),
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1604, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\model.py", line 1163, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in load_mask
    class_ids = np.array([self.class_names.index(s) for s in shapes])
  File "C:\Users\Lenovo\segmentation-unet-maskrcnn\maskRCNN\mrcnn_dataset.py", line 70, in <listcomp>
    class_ids = np.array([self.class_names.index(s) for s in shapes])
ValueError: 'C:\\Users\\Lenovo\\segmentation-unet-maskrcnn\\data\\maskRCNN\\polygon\\fieldborders' is not in list

**Comment by SomayeKarimpour** [comment]
@Riyank7 I have the same problem. Could you solve it?
